language: cpp
compiler:
  - gcc
  - clang
before_install:
  - lsb_release -c;
  - lsb_release -r;
  - which $CXX
  - which $CC
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted';
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu utopic main universe multiverse restricted';
  - sudo apt-get -y update;
  - sudo apt-get -y purge gcc g++;
  - sudo apt-get -y purge '^clang.*' '^llvm.*';
  - sudo rm -rf /usr/local/clang* /usr/local/llvm*
  - sudo apt-get -y autoremove --purge;

install:
  - sudo apt-get --no-install-recommends -y install g++;
  - sudo apt-get --no-install-recommends -y install clang;
  - if (clang --version | grep 'clang version 3\.3'); then
      sudo apt-get --no-install-recommends -y install libclang-common-3.3-dev;
    fi
  - sudo apt-get --no-install-recommends -y install libboost-dev
  - sudo apt-get --no-install-recommends -y install libboost-tools-dev;
  - sudo apt-get --no-install-recommends -y install libboost-test-dev
  - sudo apt-get -y autoremove --purge;
# Uncomment the followint to enable coveralls support.
#  - sudo pip install cpp-coveralls;

before_script:
  - ! 'echo ''project yaul-tml :
                requirements
                <include>include
                <toolset>gcc:<cxxflags>-std=c++11
                <toolset>gcc:<cxxflags>-Wextra
                <toolset>gcc:<cxxflags>-pedantic
                <toolset>clang:<cxxflags>-std=c++11
                <toolset>clang:<cxxflags>-Wextra
                <toolset>clang:<cxxflags>-pedantic
                : 
                build-dir bin.v2 ;'' > Jamroot'
  - $CXX --version;
  - $CXX -dumpversion;
  - which $CXX
  - which $CC

script:
  - bjam toolset=$CC -d+2 -a test example
  - bjam toolset=$CC -d+2 -a test test
    
# Uncomment the following block to enable code coverage support.
#after_success:
#    GCOV=gcov-`$CXX -dumpversion | sed -e 's/^\([0-9]\+\.[0-9]\+\).*$/\1/'`;
#    which $GCOV || GCOV="";
#    echo "gcov: $GCOV";
#    if [ ! -z "$GCOV" ]; then
#      coveralls --gcov $GCOV --gcov-options '\-p \-l' -b . -r . -e .git
#                 -e CMakeFiles -e docs -e /usr;
#    fi

# Use after_failure to reveal *.log files that were generated during config
# phase and so on. We should print to console as much information as we can,
# to quickly find the cause of a failure.
#after_failure:
#  - ...
